Fix error with ANNUAL series: events[COL.START].year, AttributeError: 'Series' object has no attribute 'year'
To get a list containing the years of the events, we need to get the year attribute from each entry in events[COL.START].